name: "Dockge"
description: "A fancy, easy-to-use and reactive self-hosted docker compose.yaml stack-oriented manager"
version: "1.0.2"
slug: "dockge"
init: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
url: "https://github.com/artt652/hassio-addons/tree/main/dockge"
panel_icon: mdi:docker
webui: http://[HOST]:[PORT:5001]/
read_only: false
docker_api: true

# пробрасываем только config, чтобы Dockge писал свои настройки туда
map:
  - config:rw
  - share:rw

ports:
  5001/tcp: 5001

image: "louislam/dockge"
